import 'package:json_annotation/json_annotation.dart';

part 'meta_model.g.dart'; // This is generated by running flutter pub run build_runner build

@JsonSerializable()
class MetaModel {
  @JsonKey(name: 'current_rows')
  final int? currentRows;
  @JsonKey(name: 'total_rows')
  final int? totalRows;
  @JsonKey(name: 'rows_remaining')
  final int? rowsRemaining;
  @JsonKey(name: 'total_pages')
  final int? totalPages;
  @JsonKey(name: 'pages_remaining')
  final int? pagesRemaining;
  @JsonKey(name: 'previous_page')
  final String? previousPage;
  @JsonKey(name: 'previous_page_offset')
  final int? previousPageOffset;
  @JsonKey(name: 'next_page')
  final String? nextPage;
  @JsonKey(name: 'next_page_offset')
  final int? nextPageOffset;

  MetaModel({
    required this.currentRows,
    required this.totalRows,
    required this.rowsRemaining,
    required this.totalPages,
    required this.pagesRemaining,
    this.previousPage,
    this.previousPageOffset,
    this.nextPage,
    required this.nextPageOffset,
  });

  factory MetaModel.fromJson(Map<String, dynamic> json) =>
      _$MetaModelFromJson(json);
  Map<String, dynamic> toJson() => _$MetaModelToJson(this);
}

// Run flutter pub run build_runner build to generate the meta_model.g.dart file
